---
title: Introduction to SUSE Linux Base Container Images
description: SUSE Linux Base Container Images provide a set of container images that are truly open, flexible and secure.
---

SUSE Linux Base Container Images (SUSE Linux BCI) provide a set of container
images that are truly open, flexible and secure. They are designed to provide
the foundation for your cloud native applications, enabling you to build,
deploy and share freely distributable SLES-based container images provided by
SUSE.

SUSE Linux BCI is based on SUSE Linux Enterprise Server (SLES) 15 and 16. It is
compatible with SLES without a subscription. Likewise, it features the same
predictable enterprise lifecycle as SLES. The free BCI repository
(which is a subset of the SLES repository) provides access to over 4,000
packages. The packages in this repository undergo quality assurance and security
audits by SUSE.

Additionally, SUSE offers L3 support for SUSE Linux BCI through SUSE
subscription plans.

== Security

To ensure a secure supply chain, SUSE signs all container images. Packages in
the free BCI repository undergo the same security audits as SLES. Likewise,
SUSE Linux BCI benefits from the same CVE mitigation as SLES.

== Stability

Since SUSE Linux BCI is based on SLES, it features the same level of stability,
quality assurance, and enterprise lifecycle. The container images receive
regular maintenance updates. These updates provide bug fixes, improvements and
security patches.

== Integration

SUSE Linux BCI works on any OCI-compliant runtime and Linux OS. No vendor
lock-in. Drop-in replacements are available for selected container images
from https://hub.docker.com[Docker Hub].

== Redistribution

The https://www.suse.com/licensing/eula/#bci[SUSE Linux BCI EULA] allows you to
redistribute container images based on SUSE Linux BCI. No subscription required;
ideal for development and production deployments.
