---
title: Frequently Asked Questions
description: The FAQ is designed to answer the questions our users most frequently ask about SUSE Linux Base Container Images.
slug: faq
---

== Availability and Requirements

=== Where can I find SUSE Linux BCI?

The container images are available on the https://registry.suse.com/[SUSE Container Registry].

=== On which hardware platforms is SUSE Linux BCI available?

SUSE Linux BCI is available on amd64 (x86_64), arm64 (aarch64), ppc64le and s390x.
However, architecture availability may vary depending on the specific image.

=== Do I need a subscription to use SUSE Linux BCI?

No, you can use SUSE Linux BCI for free without a subscription. Just pull the images from the https://registry.suse.com/[SUSE Container Registry] and start using them.

SUSE Linux BCI under an active SUSE Linux Enterprise Server subscription provides full support and access to SLES repositories.

=== Do I need a SUSE host to build BCI-based images?

No, you can build and run SUSE Linux BCI in any Linux environment that supports OCI-compatible images.

=== Do I need a SUSE host to deploy SUSE Linux BCI?

No, you can deploy SUSE Linux BCI to any OCI-compatible runtime or certified Kubernetes deployment.

== Contents and Customization

=== What is included in SUSE Linux BCI?

Leveraging SUSE's industry-leading build pipeline, SUSE Linux BCI provides a set of container images where all binaries are built and maintained by SUSE, drawing directly from the trusted SLES codebase.

Base containers come in several flavors. Choose the BCI Micro image for a minimal footprint or the BCI Base image with full package-management tools. Expand the container images easily using thousands of packages from the <<free-bci-repo, free BCI repository>>.

Language containers are available as a base environment for development and deployment. Use programming languages such as C++, Go, Java (OpenJDK), .NETfootnote:[Available in Tech Preview, .NET binaries provided and maintained by Microsoft.], Node.js, PHP, Python, Ruby and Rust.

Application containers provide ready-to-use databases, tools and more. Use applications such as 389 Directory Server, Cosign, Git, Helm, MariaDB, Nginx, Performance Co-Pilot, PostgreSQL, RMT and Valkey.

=== What is the difference between SUSE Linux BCI Base, Minimal, Micro and BusyBox?

The SUSE Linux BCI Base container has Zypper and access to the <<free-bci-repo, free BCI repository>>. This allows you to install any packages from the available repositories.

The SUSE Linux BCI Minimal container has RPM but does not include Zypper. It is an image designed for deployment scenarios where you copy the final artifacts to it.

The SUSE Linux BCI Micro container does not include Zypper and RPM. It is similar to BCI Minimal but designed for the deployment of static binaries.

The SUSE Linux BCI BusyBox container has no GPLv3-licensed software, Zypper, or RPM. It is comparable to BCI Micro, but it replaces the GNU Coreutils with BusyBox tools.

=== What is the free BCI repository?
[[free-bci-repo]]
The free BCI repository is a repository with packages that are free to use and redistribute, subject to the terms of the https://www.suse.com/licensing/eula/#bci[SUSE Linux BCI EULA].

All container images with Zypper include the free BCI repositories pre-configured.

=== What packages and libraries can I use to expand SUSE Linux BCI?

The container images that include Zypper have access to the <<free-bci-repo, free BCI repository>>. This repository contains thousands of SUSE-supported packages. SUSE will support these packages when the container is running on a SUSE host with the appropriate subscription.

You are also free to configure repositories from openSUSE Leap or other compatible sources.

=== Does SUSE Linux BCI have FIPS mode images?

Yes, FIPS mode container images are available.

BCI Base FIPS configures FIPS mode enabled by default. However, it does not include any certified binaries.

BCI Go includes a FIPS 140-3 enabled Go.

== Distribution

=== Can I distribute BCI-based images?

Yes, BCI-based images can be freely distributed as long as you follow the https://www.suse.com/licensing/eula/#bci[SUSE Linux BCI EULA].

All packages in the <<free-bci-repo, free BCI repository are>> freely redistributable. If you use only this repository, your container remains redistributable.

If you add more content to your container, you may need to check for additional restrictions.

=== Can I distribute BCI-based images on any registry?

Yes, you can distribute your BCI-based image in any form or registry you want.

=== Can I add third-party software to BCI-based images and still redistribute them?

Yes, but adding third-party software or repositories implies restrictions at their respective layers.

SUSE places no restrictions on redistributing the results, as long as you follow the https://www.suse.com/licensing/eula/#bci[SUSE Linux BCI EULA].

== Maintenance and Lifecycle

=== Does SUSE Linux BCI receive regular package updates?

Yes, container images receive frequent security updates and version upgrades. It follows the same principles and release model as SUSE Linux Enterprise Server.

=== Does SUSE Linux BCI receive regular security updates?

Yes, container images are rebuilt regularly and updated with SUSE's enterprise-grade security updates.

=== What is the lifecycle of SUSE Linux BCI?

The SLES-based container images follow the same support lifecycle as their SLES release.

Application and Language images follow the lifecycle of their respective tools rather than the SLES release. For further details, check the https://www.suse.com/lifecycle[SUSE Product Support Lifecycle].

Long Term Service Pack (LTSS) versions of SUSE Linux BCI are available to customers with an LTSS subscription.

== Support and Feedback

=== How is SUSE Linux BCI supported?

As a free-to-use product under the https://www.suse.com/licensing/eula/#bci[SUSE Linux BCI EULA], SUSE Linux BCI receives community support.

When BCI-based containers run on a SUSE host with an active subscription, they receive the same support as the host. This also applies to any packages installed from the <<free-bci-repo, free BCI repository>>.

You can install any package from the SLES repositories covered by your subscription and receive the same support. However, packages from the SLES repositories are not redistributable.

=== Where do I report bugs with SUSE Linux BCI?

Customers and partners with active subscriptions can use the regular channels to report issues and request support.

For community support, report bugs in https://bugzilla.suse.com/[Bugzilla] under *PUBLIC SUSE Linux Base Container Images*.

=== Where do I report issues with SUSE Linux BCI documentation?

Report issues with documentation, guides and examples in https://bugzilla.suse.com/[Bugzilla] under *PUBLIC SUSE Linux Base Container Images*.

=== Can I request packages and images to be added to SUSE Linux BCI?

Yes, you can request new features, but these require evaluation.

Customers and partners with active subscriptions can use the regular channels to request new features.

For community support, report bugs in https://bugzilla.suse.com/[Bugzilla] under *PUBLIC SUSE Linux Base Container Images*.
