---
title: General Purpose Images
description: Quick overview of the main differences between general-purpose SUSE Linux Base Container Images.
slug: general-purpose-bci
---

The general-purpose container images include a minimum set of packages
to keep their size small. You can use it as a starting point for building
other container images or for deploying specific software using the free BCI
repository.

A complete list of images is available
https://registry.suse.com/repositories?sort=featured&categories%5B%5D=bci[here].

== Base—When you need flexibility

Image repository: `registry.suse.com/bci/bci-base`

The Base image comes with a package manager (Zypper and RPM) and the free SUSE
Linux BCI repository pre-configured, allowing you to install packages from the
repository and customize the image.

== Init—When you need a Systemd environment

Image repository: `registry.suse.com/bci/bci-init`

The Init image adds https://systemd.io/[Systemd] on top of the Base image.
This container is only supported with Podman.

== Minimal—When you do not need Zypper

Image repository: `registry.suse.com/bci/bci-minimal`

The Minimal image is a stripped-down version of Base. It comes with the RPM
package manager but not Zypper, reducing its size. However, while RPM can
install and remove packages, it lacks support for repositories and automated
dependency resolution.

== Micro—When you need a small image

Image repository: `registry.suse.com/bci/bci-micro`

The Micro image has fewer preinstalled packages and no package managers. It is
ideal for deploying binaries compiled externally or in a previous build stage.

We recommend using Micro as the final stage in a
https://docs.docker.com/build/building/multi-stage/[multi-stage build] when
deploying a project.

== BusyBox—When you need the smallest and GPLv3-free image

Image repository: `registry.suse.com/bci/bci-busybox`

The BusyBox image includes tools provided by https://busybox.net/[BusyBox].
This image is smaller than Micro and contains no GPLv3-licensed software.

When using BusyBox tools, keep in mind that they differ from GNU Coreutils.
Scripts written for Bash or coreutils may require modification.

== FIPS—When you need validated, encrypted modules

Image repository:

* Base: `registry.suse.com/bci/bci-base-fips`
* Micro: `registry.suse.com/bci/bci-micro-fips`

The Base and Micro images are also offered with FIPS mode enabled. However, it
does not include any certified binaries. FIPS images with certified binaries are
available through an
https://www.suse.com/products/long-term-service-pack-support/[LTSS subscription].

Use these images in deployment scenarios that require FIPS 140-2 or FIPS 140-3.

== Approximate image size

Below are the approximate sizes of each image.

* SUSE Linux BCI Base ~100-120 MB
* SUSE Linux BCI Base FIPS ~150-175 MB
* SUSE Linux BCI Init ~140-150 MB
* SUSE Linux BCI Minimal ~35-45 MB
* SUSE Linux BCI Micro ~25 MB
* SUSE Linux BCI Micro FIPS ~35 MB
* SUSE Linux BCI BusyBox ~15 MB
