---
title: Language Stack Images
description: Quick overview of language stack SUSE Linux Base Container Images, such as Go, Python and Rust.
slug: language-stack-bci
---

The language stack container images include the most common tools for building
and deploying applications in their specific language environment. This includes
tools like a compiler or interpreter, as well as the language-specific package
manager.

These images are built on top of SUSE Linux BCI Base and have the free BCI
repository pre-configured.

A complete list of images is available
https://registry.suse.com/repositories?sort=featured&categories%5B%5D=bci-devel[here].

== C/C++

Image repository: `registry.suse.com/bci/gcc`

The https://registry.suse.com/repositories?languages%5B%5D=cpp[C/C++ image]
includes the GNU Compiler Collection version specified in the tag, as well as
cURL, Git, GNU make and Fortran.

== Go

Image repository: `registry.suse.com/bci/golang`

The https://registry.suse.com/repositories?languages%5B%5D=go[Go image] includes
the Go compiler version specified in the tag, as well as cURL, Git and GNU make.

== Node.js

Image repository: `registry.suse.com/bci/nodejs`

The https://registry.suse.com/repositories?languages%5B%5D=nodejs[Node.js image]
includes the Node.js version specified in the tag, as well as cURL, Git and npm.

You can install https://yarnpkg.com/[Yarn] with the following command:

[source,ShellSession]
----
npm install -g yarn
----

== OpenJDK

Image repository:

* Runtime: `registry.suse.com/bci/openjdk`
* Development: `registry.suse.com/bci/openjdk-devel`

The https://registry.suse.com/repositories?languages%5B%5D=openjdk[OpenJDK images]
include the OpenJDK Runtime version specified in the tag, as well as cURL and Git.

The development image also includes the OpenJDK Development Environment and
https://maven.apache.org/[Maven].

== Python

Image repository: `registry.suse.com/bci/python`

The https://registry.suse.com/repositories?languages%5B%5D=python[Python image]
includes the Python version specified in the tag, as well as cURL, Git and Pip.
Pipx and wheel are also available on selected versions.

== PHP

Image repository:

* PHP: `registry.suse.com/bci/php`
* PHP with Apache: `registry.suse.com/bci/php-apache`
* PHP with FPM: `registry.suse.com/bci/php-fpm`

The https://registry.suse.com/repositories?languages%5B%5D=php[PHP image]
includes the PHP version specified in the tag, as well as Composer and selected
PHP extensions.

The Apache variant also includes the https://httpd.apache.org/[Apache HTTP Server].

The FPM variant also includes the http://php.net/manual/en/install.fpm.php[FastCGI Process Manager (FPM)]

== Ruby

Image repository: `registry.suse.com/bci/ruby`

The https://registry.suse.com/repositories?languages%5B%5D=ruby[Ruby image]
includes the Ruby version specified in the tag, as well as cURL, Git, Bundler
and Gem. It also includes Rails dependencies, such as C++, GNU make and SQLite.

== Rust

Image repository: `registry.suse.com/bci/rust`

The https://registry.suse.com/repositories?languages%5B%5D=rust[Rust image]
includes the Rust and Cargo versions specified in the tag.

== .NET

Image repository:

* Runtime: `registry.suse.com/bci/dotnet-runtime`
* SDK: `registry.suse.com/suse/dotnet-sdk`
* ASP.NET Core Runtime: `registry.suse.com/bci/dotnet-aspnet`

The https://registry.suse.com/repositories?sort=featured&languages%5B%5D=dotnet[.NET images]
include the .NET version specified in the tag.

Microsoft provides the .NET packages through the https://learn.microsoft.com/en-us/dotnet/core/install/linux-sles[Microsoft package feed]. As the .NET packages in this image are from
a third-party repository, SUSE doesn't provide support or warranties for such
packages.
