---
title: Language stack SLE Base Container Images
slug: language-stack-bci
---

If you have a working knowledge of containers, you will not have any
difficulties using SLE BCIs. However, there are certain features that
set SLE BCIs apart from similar offerings, like images based on Debian
or Alpine Linux. And understanding the specifics can help you to get the
most out of SLE BCIs in the shortest time possible.

== Language stack SLE BCIs

Language stack SLE BCI are built on top of BCI-Base. Below is an
overview of the available language stack SLE BCIs.

=== Python

* repository: https://registry.suse.com/repositories?languages%5B%5D=python[`registry.suse.com/bci/python`]

Ships with the python3 version from the tag and pip3, curl, git tools.

=== Node

* repository: https://registry.suse.com/repositories?languages%5B%5D=nodejs[`registry.suse.com/bci/node`]

Comes with nodejs version from the tag, npm and git. The yarn package
manager can be installed with the `npm install -g yarn` command.

=== OpenJDK

* repository: https://registry.suse.com/repositories?languages%5B%5D=openjdk[`registry.suse.com/bci/openjdk`]

Ships with the OpenJDK runtime. Designed for deploying Java applications.

=== OpenJDK (devel)

* repository: https://registry.suse.com/repositories?languages%5B%5D=openjdk[`registry.suse.com/bci/openjdk-devel`]

Includes the development part of OpenJDK in addition to the OpenJDK
runtime. Instead of Bash, the default entry point is the jshell shell.

=== Ruby

* repository: https://registry.suse.com/repositories?languages%5B%5D=ruby[`registry.suse.com/bci/ruby`]

A standard development environment featuring ruby, gem and bundler as well as git and curl.

=== Go

* repository: https://registry.suse.com/repositories?languages%5B%5D=go[`registry.suse.com/bci/golang`]

Ships with the go compiler version specified in the tag.

=== .NET (runtime)

* repository: https://registry.suse.com/repositories?sort=featured&languages%5B%5D=dotnet[`registry.suse.com/bci/dotnet-runtime`]

Includes the .NET runtime from Microsoft and the Microsoft .NET
repository.

=== .NET (aspnet)

* repository: https://registry.suse.com/repositories?sort=featured&languages%5B%5D=dotnet[`registry.suse.com/bci/dotnet-aspnet`]

Ships with the ASP.NET runtime from Microsoft and the Microsoft .NET
repository.

=== .Net (SDK)

* repository: https://registry.suse.com/repositories?sort=featured&languages%5B%5D=dotnet[`registry.suse.com/suse/dotnet-sdk`]

Comes with the .NET and ASP.NET SDK from Microsoft as well as the Microsoft .NET repository.

=== PHP

* repository: https://registry.suse.com/repositories?languages%5B%5D=php[`registry.suse.com/bci/php:latest`]

Ships with support for installing additional PHP extensions.


=== C/C++

* repository: https://registry.suse.com/repositories?languages%5B%5D=cpp[`registry.suse.com/bci/gcc`]

Includes also the support for Fortran.

=== Rust

* repository: https://registry.suse.com/repositories?languages%5B%5D=rust[`registry.suse.com/bci/rust`]

Ships with the Rust compiler and the cargo package manager.
