---
title: Verify SLE Base Container Images With Cosign
slug: verify-with-cosign
---

== Introduction

Verifying container images allows you to confirm their provenance, thus ensuring
the supply chain security. As an alternative to the existing solutions, it is
possible to use https://github.com/SigStore/cosign[Cosign] for verifying
container images.

== Verifying BCIs with Cosign

To verify a BCI, run Cosign in the container. The command below fetches the
signing key from the SUSE server and uses it to verify the latest BCI-Base container
image.

[source,ShellSession]
----
> podman run --rm -it gcr.io/projectsigstore/cosign verify \
    --key https://ftp.suse.com/pub/projects/security/keys/container–key.pem \
    registry.suse.com/bci/bci-base:latest | tail -1 | jq

[
  {
    "critical": {
      "identity": {
        "docker-reference": "registry.suse.com/bci/bci-base"
      },
      "image": {
        "docker-manifest-digest": "sha256:52a828600279746ef669cf02a599660cd53faf4b2430a6b211d593c3add047f5"
      },
      "type": "cosign container image signature"
    },
    "optional": {
      "creator": "OBS"
    }
  }
]
----

The signing key can be used to verify all BCI container images, and it also
ships with SLE 15 (the `/usr/share/container-keys/suse-container-key.pem` file).

You can also check BCI container images against
https://github.com/sigstore/rekor[rekor], the immutable tamper resistant
ledger. For example:

[source,ShellSession]
----
> podman run --rm -it -e COSIGN_EXPERIMENTAL=1 gcr.io/projectsigstore/cosign \
    verify --key https://ftp.suse.com/pub/projects/security/keys/container–key.pem \
    registry.suse.com/bci/bci-base:latest | tail -1 | jq
[
  {
    "critical": {
      "identity": {
        "docker-reference": "registry.suse.com/bci/bci-base"
      },
      "image": {
        "docker-manifest-digest": "sha256:52a828600279746ef669cf02a599660cd53faf4b2430a6b211d593c3add047f5"
      },
      "type": "cosign container image signature"
    },
    "optional": {
      "creator": "OBS"
    }
  }
]
----

If verification fails, the output of the `cosign verify` command is similar to the one below.

----
Error: no matching signatures:
crypto/rsa: verification error
main.go:62: error during command execution: no matching signatures:
crypto/rsa: verification error
----